(() => {
'use strict';
const builtin=[{id:'bd-tv-27',number:27,name:'BD TV',category:'Bangla',genre:'News',language:'Bangla',country:'Bangladesh',logo:'https://i.imgur.com/WpMA9kC.png',url:'http://livetv.akr4m.com:8080/bdtv/restrem/27.m3u8',type:'hls',addedAt:'2026-01-01'}];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k));return x==null?d:x}catch{return d}};
const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const state={channels:[],current:null,hls:null,dash:null,category:'All',country:'All',language:'All',genre:'All',search:'',sort:'recommended',theme:read('sh_theme','dark'),favorites:read('sh_fav',[]),hidden:read('sh_hidden',[]),watched:read('sh_watch',[]),plays:read('sh_plays',{}),events:read('sh_events',[]),settings:{autoplay:true,quality:'auto',category:'All',controls:true,language:'English',pin:''},lastPosition:read('sh_pos',{})};
const save=()=>{write('sh_fav',state.favorites);write('sh_hidden',state.hidden);write('sh_watch',state.watched.slice(0,50));write('sh_plays',state.plays);write('sh_events',state.events.slice(-500));write('sh_pos',state.lastPosition);write('sh_theme',state.theme);if(window.TVDB) Promise.all([TVDB.set('favorites',state.favorites),TVDB.set('watched',state.watched),TVDB.set('plays',state.plays),TVDB.set('events',state.events.slice(-500)),TVDB.set('positions',state.lastPosition)]).catch(()=>{})};
async function init(){
 let ext=Array.isArray(window.DEFAULT_CHANNELS)?window.DEFAULT_CHANNELS:[], remote=[];
 try{const r=await fetch('/api/data');if(r.ok){const j=await r.json();if(j.mongo&&Array.isArray(j.channels))remote=j.channels}}catch{}
 let local=read('sh_channels',[]);const all=[...builtin,...ext,...remote,...local];const map=new Map();for(const c of all){if(!c?.name||!c?.url)continue;const x={id:String(c.id||`${c.name}-${c.url}`),number:Number(c.number||0),name:String(c.name),category:String(c.category||'Other'),genre:String(c.genre||c.category||'Other'),language:String(c.language||'English'),country:String(c.country||(/bangla|bangladesh/i.test(c.category||'')?'Bangladesh':'Global')),logo:String(c.logo||''),url:String(c.url),type:String(c.type||'auto').toLowerCase(),addedAt:c.addedAt||new Date().toISOString(),enabled:c.enabled!==false,epg:Array.isArray(c.epg)?c.epg:[]};if(!map.has(x.id)&&x.enabled&&!state.hidden.includes(x.id))map.set(x.id,x)}state.channels=[...map.values()];
 applyTheme(); bindGlobal(); render();
}
function applyTheme(){document.documentElement.classList.toggle('light',state.theme==='light');const b=$('#themeBtn');if(b)b.textContent=state.theme==='dark'?'☀':'☾'}
function categories(key){return ['All',...new Set(state.channels.map(c=>c[key]).filter(Boolean))]}
function type(c){if(c.type!=='auto')return c.type;const u=c.url.toLowerCase().split(/[?#]/)[0];if(/\.m3u8$/.test(u))return'hls';if(/\.mpd$/.test(u))return'dash';if(/\.(mp4|webm|ogg|ogv|m4v)$/.test(u))return'video';if(/youtube\.com|youtu\.be|vimeo\.com|dailymotion\.com|dai\.ly/.test(u))return'embed';return'video'}
function playable(c){if(type(c)==='hls'&&/^http:\/\//i.test(c.url)){try{const u=new URL(c.url);if(u.hostname.toLowerCase()==='livetv.akr4m.com')return `/api/proxy?url=${encodeURIComponent(c.url)}`}catch{}}return c.url}
function initials(n){const a=String(n||'TV').trim().split(/\s+/).filter(Boolean);return(a.length>1?a[0][0]+a.at(-1)[0]:a[0].slice(0,2)).toUpperCase()}
function card(c){const fav=state.favorites.includes(c.id);return `<article class="channel-card" tabindex="0" data-id="${esc(c.id)}"><div class="logo-box">${c.logo?`<img src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}<span class="logo-fallback" style="${c.logo?'display:none':''}">${esc(initials(c.name))}</span><span class="live-badge">LIVE</span><button class="star-btn ${fav?'on':''}" data-fav="${esc(c.id)}" tabindex="-1" type="button">${fav?'★':'☆'}</button></div><div class="card-body"><div class="channel-name">${esc(c.name)}</div><div class="channel-meta">${esc(c.country)} · ${esc(c.genre)}</div></div></article>`}
function bindCards(root){$$(root+' .channel-card').forEach(el=>{el.addEventListener('click',e=>{const f=e.target.closest('[data-fav]');if(f){toggleFav(f.dataset.fav);return}openPath(`/play?id=${encodeURIComponent(el.dataset.id)}`)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPath(`/play?id=${encodeURIComponent(el.dataset.id)}`)}if(e.key.toLowerCase()==='f'){e.preventDefault();toggleFav(el.dataset.id)}})});$$(`${root} [data-fav]`).forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)})}
function openPath(p){history.pushState({},'',p);render()}
function route(){return location.pathname.replace(/\/+$/,'')||'/home'}
function render(){ $$('.page').forEach(x=>x.classList.add('hidden'));const r=route();if(r==='/channels'){$('#channelsPage').classList.remove('hidden');renderChannels()}else if(r==='/play'){$('#playPage').classList.remove('hidden');openPlay(new URLSearchParams(location.search).get('id'))}else if(r==='/favorites'){$('#favoritesPage').classList.remove('hidden');renderFavorites()}else if(r==='/settings'){$('#settingsPage').classList.remove('hidden');renderSettings()}else if(r==='/admin'){$('#adminPage').classList.remove('hidden');renderAdmin()}else{$('#homePage').classList.remove('hidden');renderHome()} window.scrollTo(0,0);focusFirst()}
function shelf(title,list,href='/channels'){return `<section class="section shelf"><div class="section-title"><h2>${esc(title)}</h2><a href="${href}">See all →</a></div><div class="rail">${list.length?list.slice(0,16).map(card).join(''):'<div class="empty-shelf">Nothing here yet.</div>'}</div></section>`}
function renderHome(){
 $('#homeCount').textContent=state.channels.length;$('#homeCategories').innerHTML=categories('category').map(c=>`<button class="category-btn ${c==='All'?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');
 $$('#homeCategories .category-btn').forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;renderHomeShelves()});
 const latest=state.watched.map(id=>state.channels.find(c=>c.id===id)).filter(Boolean);$('#latestRow').innerHTML=latest.length?latest.map(card).join(''):'<div class="empty-shelf">Watch a channel and it will appear here.</div>';bindCards('#latestRow');
 const recent=state.channels.filter(c=>new Date(c.addedAt).getTime()).sort((a,b)=>new Date(b.addedAt)-new Date(a.addedAt));$('#recentRow').innerHTML=recent.length?recent.map(card).join(''):'<div class="empty-shelf">No recently added channels.</div>';bindCards('#recentRow');
 const pop=[...state.channels].sort((a,b)=>(state.plays[b.id]||0)-(state.plays[a.id]||0)||a.name.localeCompare(b.name));$('#popularRow').innerHTML=pop.map(card).join('');bindCards('#popularRow');
 const trend=trending();$('#trendingRow').innerHTML=trend.map(card).join('');bindCards('#trendingRow');
 const rec=recommended();$('#recommendedRow').innerHTML=rec.map(card).join('');bindCards('#recommendedRow');renderHomeShelves();
}
function renderHomeShelves(){const cat=state.category||'All';const cats=cat==='All'?categories('category').slice(1):[cat];$('#homeShelves').innerHTML=cats.map(c=>shelf(c,state.channels.filter(x=>x.category===c),`/channels?category=${encodeURIComponent(c)}`)).join('');bindCards('#homeShelves')}
function trending(){const now=Date.now(),windowMs=7*86400000;const scores={};for(const e of state.events){if(now-e.t<windowMs)scores[e.id]=(scores[e.id]||0)+1}return [...state.channels].sort((a,b)=>(scores[b.id]||0)-(scores[a.id]||0)||(state.plays[b.id]||0)-(state.plays[a.id]||0)).slice(0,16)}
function recommended(){const cats={};for(const id of state.watched){const c=state.channels.find(x=>x.id===id);if(c)cats[c.category]=(cats[c.category]||0)+1}const fav=state.channels.filter(c=>state.favorites.includes(c.id));return [...state.channels].filter(c=>!state.watched.includes(c.id)).sort((a,b)=>((cats[b.category]||0)+(state.favorites.includes(b.id)?3:0))-((cats[a.category]||0)+(state.favorites.includes(a.id)?3:0))).slice(0,16)}
function renderChannels(){const p=new URLSearchParams(location.search);if(p.get('category'))state.category=p.get('category');if(!categories('category').includes(state.category))state.category='All';['category','country','language','genre'].forEach(k=>{const el=$(`#filter-${k}`);if(el)el.innerHTML=categories(k).map(x=>`<option>${esc(x)}</option>`).join('');if(el)el.value=state[k]||'All'});applyFilters()}
function applyFilters(){let r=state.channels.filter(c=>(state.category==='All'||c.category===state.category)&&(state.country==='All'||c.country===state.country)&&(state.language==='All'||c.language===state.language)&&(state.genre==='All'||c.genre===state.genre)&&(!state.search||`${c.name} ${c.category} ${c.country} ${c.language} ${c.genre}`.toLowerCase().includes(state.search.toLowerCase())));if(state.sort==='az')r.sort((a,b)=>a.name.localeCompare(b.name));else if(state.sort==='category')r.sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));else if(state.sort==='popular')r.sort((a,b)=>(state.plays[b.id]||0)-(state.plays[a.id]||0));$('#resultCount').textContent=`${r.length} channels`;$('#channelGrid').innerHTML=r.length?r.map(card).join(''):'<div class="empty-state">No channels found.</div>';bindCards('#channelGrid')}
function toggleFav(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[id,...state.favorites];save();render()}
function renderFavorites(){const list=state.channels.filter(c=>state.favorites.includes(c.id));$('#favoriteGrid').innerHTML=list.length?list.map(card).join(''):'<div class="empty-state">No favorites yet. Press ☆ on a channel.</div>';bindCards('#favoriteGrid')}
function cleanup(){if(state.hls){try{state.hls.destroy()}catch{}state.hls=null}if(state.dash){try{state.dash.reset()}catch{}state.dash=null}const v=$('#videoPlayer');if(v){v.pause();v.removeAttribute('src');v.load();v.onloadedmetadata=null;v.onerror=null}$('#embedPlayer').src='about:blank'}
function loading(on,msg='Connecting to live stream…'){$('#loadingOverlay').classList.toggle('hidden',!on);$('#loadingText').textContent=msg}
function error(msg){loading(false);$('#errorOverlay').classList.remove('hidden');$('#errorText').textContent=msg}
function record(c){state.watched=[c.id,...state.watched.filter(x=>x!==c.id)].slice(0,50);state.plays[c.id]=(state.plays[c.id]||0)+1;state.events.push({id:c.id,t:Date.now()});save()}
function openPlay(id){const c=state.channels.find(x=>x.id===id)||state.channels[0];if(!c)return; if(state.current?.id!==c.id){cleanup();state.current=c;record(c)}$('#playTitle').textContent=c.name;$('#playCountry').textContent=c.country;$('#playCategory').textContent=c.genre;$('#playType').textContent=type(c).toUpperCase();$('#playLogo').src=c.logo||'';$('#errorOverlay').classList.add('hidden');loading(true);renderRelated(c);renderEPG(c);startPlayer(c)}
function renderRelated(c){const r=state.channels.filter(x=>x.id!==c.id).sort((a,b)=>(a.category===c.category?0:1)-(b.category===c.category?0:1)).slice(0,18);$('#relatedCount').textContent=r.length;$('#relatedRow').innerHTML=r.length?r.map(card).join(''):'<div class="empty-shelf">No related channels.</div>';bindCards('#relatedRow')}
function renderEPG(c){const epg=c.epg.length?c.epg:[{time:'LIVE',title:c.name+' Live'}];$('#epgRow').innerHTML=epg.slice(0,8).map(x=>`<div class="epg-item"><b>${esc(x.time||'')}</b><span>${esc(x.title||'')}</span></div>`).join('')}
function startPlayer(c){const t=type(c);if(t==='hls')return playHls(c);if(t==='dash')return playDash(c);if(t==='embed')return playEmbed(c);return playVideo(c)}
function playHls(c){const v=$('#videoPlayer'),url=playable(c);v.style.display='block';$('#embedPlayer').style.display='none';if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=url;v.onloadedmetadata=()=>begin(v,c);v.onerror=()=>retryable(c);return}if(!window.Hls?.isSupported())return error('HLS is not supported on this TV browser.');const h=new Hls({enableWorker:true,lowLatencyMode:true,backBufferLength:10,maxBufferLength:12,maxMaxBufferLength:20,capLevelToPlayerSize:true,startLevel:-1,autoStartLoad:true,liveSyncDurationCount:2,liveMaxLatencyDurationCount:5});state.hls=h;h.loadSource(url);h.attachMedia(v);h.on(Hls.Events.MANIFEST_PARSED,()=>{setupQuality(h);begin(v,c)});h.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){try{if(d.type===Hls.ErrorTypes.NETWORK_ERROR){h.startLoad()}else if(d.type===Hls.ErrorTypes.MEDIA_ERROR){h.recoverMediaError()}else retryable(c)}catch{retryable(c)}}});}
function setupQuality(h){const s=$('#qualitySelect');if(!s)return;s.innerHTML='<option value="auto">Auto</option>'+h.levels.map((l,i)=>`<option value="${i}">${l.height?l.height+'p':Math.round(l.bitrate/1000)+' kbps'}</option>`).join('');s.onchange=()=>{h.currentLevel=s.value==='auto'?-1:Number(s.value)};const a=$('#audioSelect');a.innerHTML=h.audioTracks?.length?h.audioTracks.map((x,i)=>`<option value="${i}">${esc(x.name||x.lang||('Audio '+(i+1)))}</option>`).join(''):'<option>Audio</option>'}
function playDash(c){const v=$('#videoPlayer');v.style.display='block';$('#embedPlayer').style.display='none';if(!window.dashjs)return error('DASH player unavailable.');const d=window.dashjs.MediaPlayer().create();state.dash=d;d.initialize(v,playable(c),state.settings.autoplay);d.on(window.dashjs.MediaPlayer.events.STREAM_INITIALIZED,()=>begin(v,c));d.on(window.dashjs.MediaPlayer.events.ERROR,()=>retryable(c))}
function playVideo(c){const v=$('#videoPlayer');v.style.display='block';$('#embedPlayer').style.display='none';v.src=playable(c);v.onloadedmetadata=()=>begin(v,c);v.onerror=()=>retryable(c)}
function playEmbed(c){$('#videoPlayer').style.display='none';const f=$('#embedPlayer');f.style.display='block';let u=c.url;if(/youtube\.com|youtu\.be/i.test(u)){const m=u.match(/(?:v=|youtu\.be\/)([^&?/]+)/);if(m)u=`https://www.youtube.com/embed/${m[1]}?autoplay=1&playsinline=1`}else if(/dailymotion/i.test(u)){const m=u.match(/video\/([^_?]+)/);if(m)u=`https://www.dailymotion.com/embed/video/${m[1]}?autoplay=1`}f.src=u;setTimeout(()=>loading(false),900)}
function begin(v,c){loading(false);const pos=Number(state.lastPosition[c.id]||0);if(pos>5&&!v.duration?.toString().includes('Infinity')){try{v.currentTime=pos}catch{}}if(state.settings.autoplay)v.play().catch(()=>{})}
function retryable(c){error('Stream connection failed. Retrying automatically…');clearTimeout(window.__retry);window.__retry=setTimeout(()=>{if(state.current?.id===c.id){$('#errorOverlay').classList.add('hidden');cleanup();loading(true,'Reconnecting…');startPlayer(c)}},2500)}
function bindPlayer(){const v=$('#videoPlayer');v.addEventListener('timeupdate',()=>{if(state.current&&isFinite(v.currentTime)&&v.currentTime>0){state.lastPosition[state.current.id]=v.currentTime;save()}});$('#retryBtn').onclick=()=>{if(state.current){$('#errorOverlay').classList.add('hidden');cleanup();loading(true);startPlayer(state.current)}};$('#prevBtn').onclick=()=>moveChannel(-1);$('#nextBtn').onclick=()=>moveChannel(1);$('#speedSelect').onchange=e=>{v.playbackRate=Number(e.target.value)};$('#aspectSelect').onchange=e=>{$('#videoShell').style.setProperty('--ratio',e.target.value)};$('#subtitleBtn').onclick=()=>{[...v.textTracks].forEach(t=>t.mode=t.mode==='showing'?'hidden':'showing')};$('#audioSelect').onchange=e=>{if(state.hls&&state.hls.audioTracks?.length)state.hls.audioTrack=Number(e.target.value)};}
function moveChannel(dir){if(!state.current)return;const i=state.channels.findIndex(c=>c.id===state.current.id);const n=state.channels[(i+dir+state.channels.length)%state.channels.length];openPath(`/play?id=${encodeURIComponent(n.id)}`)}
function focusFirst(){setTimeout(()=>{const x=$('.page:not(.hidden) [tabindex="0"], .page:not(.hidden) button, .page:not(.hidden) a');if(x&&matchMedia('(min-width:900px)').matches)x.focus()},80)}
function bindGlobal(){
 window.onpopstate=render;$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';applyTheme();save()};$('#randomBtn').onclick=()=>{const c=state.channels[Math.floor(Math.random()*state.channels.length)];if(c)openPath(`/play?id=${encodeURIComponent(c.id)}`)};$('#searchInput').oninput=e=>{state.search=e.target.value;applyFilters();if(state.search&&route()!=='/channels')openPath('/channels')};$('#clearSearch').onclick=()=>{$('#searchInput').value='';state.search='';if(route()==='/channels')applyFilters()};
 $$('.nav-btn').forEach(a=>a.onclick=e=>{e.preventDefault();openPath(a.getAttribute('href'))});$('#sortRow').onclick=e=>{const b=e.target.closest('[data-sort]');if(!b)return;state.sort=b.dataset.sort;$$('#sortRow [data-sort]').forEach(x=>x.classList.toggle('active',x===b));applyFilters()};
 ['category','country','language','genre'].forEach(k=>{const el=$(`#filter-${k}`);if(el)el.onchange=()=>{state[k]=el.value;applyFilters()}});bindPlayer();
 document.addEventListener('keydown',tvKeys);$('#reportBtn').onclick=report;$('#saveSettings').onclick=saveSettings;$('#clearHistory').onclick=()=>{state.watched=[];state.lastPosition={};save();render()};$('#clearCache').onclick=()=>{localStorage.removeItem('sh_channels');alert('Local cache cleared.');};$('#openFavorites').onclick=()=>openPath('/favorites');$('#openSettings').onclick=()=>openPath('/settings');$('#openAdmin').onclick=()=>openPath('/admin');$('#heroRandom').onclick=()=>$('#randomBtn').click();
}
let longTimer;function tvKeys(e){if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const k=e.key;if(k==='MediaPlayPause'){const v=$('#videoPlayer');v.paused?v.play():v.pause();return}if(k==='ArrowRight'&&route()==='/play'){moveChannel(1);return}if(k==='ArrowLeft'&&route()==='/play'){moveChannel(-1);return}if(k==='ChannelUp'){moveChannel(1);return}if(k==='ChannelDown'){moveChannel(-1);return}if(k==='Escape'||k==='Backspace'||k==='GoBack'||e.keyCode===4){if(route()!=='/home'){e.preventDefault();history.back()}return}if(k.length===1&&/^[0-9]$/.test(k)){clearTimeout(longTimer);let buf=read('sh_num','')+k;write('sh_num',buf);longTimer=setTimeout(()=>{const n=Number(read('sh_num',''));localStorage.removeItem('sh_num');const c=state.channels.find(x=>x.number===n);if(c)openPath(`/play?id=${encodeURIComponent(c.id)}`)},700)}}
function renderSettings(){const s=state.settings;$('#defaultCategory').innerHTML=categories('category').map(x=>`<option>${esc(x)}</option>`).join('');$('#autoPlay').checked=s.autoplay;$('#qualityDefault').value=s.quality;$('#defaultCategory').value=s.category;$('#themeSetting').value=state.theme;$('#controlSetting').checked=s.controls;$('#languageSetting').value=s.language;}
function saveSettings(){state.settings.autoplay=$('#autoPlay').checked;state.settings.quality=$('#qualityDefault').value;state.settings.category=$('#defaultCategory').value;state.theme=$('#themeSetting').value;state.settings.controls=$('#controlSetting').checked;state.settings.language=$('#languageSetting').value;save();applyTheme();alert('Settings saved')}
function report(){if(!state.current)return;fetch('/api/report',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({channelId:state.current.id,name:state.current.name,url:state.current.url})}).catch(()=>{});alert('Issue reported')}
function renderAdmin(){const rows=state.channels.map(c=>`<tr><td>${esc(c.number||'')}</td><td>${esc(c.name)}</td><td>${esc(c.category)}</td><td><button data-edit="${esc(c.id)}">Edit</button> <button data-hide="${esc(c.id)}">Hide</button></td></tr>`).join('');$('#adminRows').innerHTML=rows;$('#adminRows').onclick=e=>{const ed=e.target.dataset.edit,hd=e.target.dataset.hide;if(ed){const c=state.channels.find(x=>x.id===ed);if(c){const n=prompt('Channel name',c.name);if(n)c.name=n;const u=prompt('Stream URL',c.url);if(u)c.url=u;write('sh_channels',state.channels);render()}}if(hd){state.hidden.push(hd);write('sh_hidden',state.hidden);location.reload()}}}
init();
})();
