(() => {
  'use strict';
  const builtin = [{id:'bd-tv-27',name:'BD TV',category:'Bangla',logo:'https://i.imgur.com/WpMA9kC.png',url:'http://livetv.akr4m.com:8080/bdtv/restrem/27.m3u8',type:'hls'}];
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const read=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k)||'null');return x==null?d:x}catch{return d}};
  const state={channels:[],category:'All',search:'',sort:'default',current:null,hls:null,dash:null,theme:localStorage.getItem('iptv_theme')||'dark',watched:read('streamhub_watched',[]),popular:read('streamhub_popular',{})};
  const initials=n=>{const a=String(n||'TV').trim().split(/\s+/).filter(Boolean);return (a.length>1?a[0][0]+a.at(-1)[0]:a[0].slice(0,2)).toUpperCase()};
  function save(){localStorage.setItem('streamhub_watched',JSON.stringify(state.watched.slice(0,30)));localStorage.setItem('streamhub_popular',JSON.stringify(state.popular))}
  function mark(c){state.watched=[c.id,...state.watched.filter(x=>x!==c.id)].slice(0,30);state.popular[c.id]=(Number(state.popular[c.id])||0)+1;save()}
  function allChannels(){
    const ext=Array.isArray(window.DEFAULT_CHANNELS)?window.DEFAULT_CHANNELS:[];
    let local=[];try{local=JSON.parse(localStorage.getItem('simple_iptv_channels')||'[]')}catch{}
    const out=[];for(const c of [...builtin,...ext,...(Array.isArray(local)?local:[])]){if(!c?.name||!c?.url)continue;const x={id:String(c.id||`${c.name}-${c.url}`),name:String(c.name),category:String(c.category||'Other'),country:String(c.country||guessCountry(c.category)),logo:String(c.logo||''),url:String(c.url),type:String(c.type||'auto').toLowerCase()};if(!out.some(y=>y.id===x.id||y.url===x.url))out.push(x)}return out;
  }
  function guessCountry(cat){return /bangla|bangladesh/i.test(cat||'')?'Bangladesh':'Global'}
  function type(c){if(c.type!=='auto')return c.type;const u=c.url.toLowerCase().split(/[?#]/)[0];if(/\.m3u8$/.test(u))return'hls';if(/\.mpd$/.test(u))return'dash';if(/\.(mp4|webm|ogg|ogv|m4v)$/.test(u))return'video';if(/youtube\.com|youtu\.be|vimeo\.com|dailymotion\.com|dai\.ly/.test(u))return'embed';return'video'}
  function playable(c){if(type(c)==='hls'&&/^http:\/\//i.test(c.url)){try{if(new URL(c.url).hostname.toLowerCase()==='livetv.akr4m.com')return`/api/proxy?url=${encodeURIComponent(c.url)}`}catch{}}return c.url}
  function card(c){return `<article class="channel-card" tabindex="0" data-id="${esc(c.id)}"><div class="logo-box">${c.logo?`<img src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'">`:''}<span class="logo-fallback" style="${c.logo?'display:none':''}">${esc(initials(c.name))}</span><span class="live-badge">LIVE</span><button class="star-btn" tabindex="-1" type="button" aria-label="Favorite">☆</button></div><div class="card-body"><div class="channel-name">${esc(c.name)}</div><div class="channel-meta">${esc(c.country)} · ${esc(c.category)} <span class="play-mini">▶</span></div></div></article>`}
  function bindCards(root){$$(root+' .channel-card').forEach(el=>{el.addEventListener('click',e=>{if(e.target.closest('.star-btn'))return;navigate(`/play?id=${encodeURIComponent(el.dataset.id)}`)});el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();navigate(`/play?id=${encodeURIComponent(el.dataset.id)}`)}})})}
  function navigate(path){history.pushState({},'',path);renderRoute()}
  function route(){return location.pathname.replace(/\/+$/,'')||'/home'}
  function renderRoute(){ $$('.page').forEach(p=>p.classList.add('hidden'));if(route()==='/channels'){ $('#channelsPage').classList.remove('hidden');renderCategories();applyFilters()}else if(route()==='/play'){$('#playPage').classList.remove('hidden');openById(new URLSearchParams(location.search).get('id')||'')}else{$('#homePage').classList.remove('hidden');renderHome()}window.scrollTo(0,0);focusFirst() }
  function categories(){return [...new Set(state.channels.map(c=>c.category).filter(Boolean))]}
  function renderCategoryStrip(id,selected,handler){const cats=['All',...categories()];$(id).innerHTML=cats.map(c=>`<button class="category-btn ${c===selected?'active':''}" data-cat="${esc(c)}" type="button">${esc(c)}</button>`).join('');$$(`${id} .category-btn`).forEach(b=>b.onclick=()=>handler(b.dataset.cat))}
  function renderHome(){
    $('#homeCount').textContent=state.channels.length;
    renderCategoryStrip('#homeCategories','All',cat=>{buildHomeShelves(cat);renderCategoryStrip('#homeCategories',cat,buildHomeShelves);});
    const latest=state.watched.map(id=>state.channels.find(c=>c.id===id)).filter(Boolean).slice(0,12);
    $('#latestRow').innerHTML=latest.length?latest.map(card).join(''):`<div class="empty-shelf">No recently watched channels yet.</div>`;bindCards('#latestRow');
    const popular=[...state.channels].sort((a,b)=>(Number(state.popular[b.id])||0)-(Number(state.popular[a.id])||0)||a.name.localeCompare(b.name)).slice(0,12);
    $('#popularRow').innerHTML=popular.length?popular.map(card).join(''):`<div class="empty-shelf">Popular channels will appear after you watch channels.</div>`;bindCards('#popularRow');
    buildHomeShelves('All');
  }
  function buildHomeShelves(selected){
    if(selected&&selected!=='All'){const list=state.channels.filter(c=>c.category===selected);$('#homeShelves').innerHTML=shelfMarkup(selected,list,true);bindCards('#homeShelves');return}
    $('#homeShelves').innerHTML=categories().map(cat=>shelfMarkup(cat,state.channels.filter(c=>c.category===cat),false)).join('');bindCards('#homeShelves');
  }
  function shelfMarkup(cat,list,showAll){const shown=list.slice(0,14);return `<section class="section shelf home-category-shelf"><div class="section-title"><h2>${esc(cat)}</h2><a href="/channels?category=${encodeURIComponent(cat)}">See all →</a></div><div class="rail">${shown.length?shown.map(card).join(''):'<div class="empty-shelf">No channels in this category.</div>'}</div></section>`}
  function renderCategories(){const urlCat=new URLSearchParams(location.search).get('category');if(urlCat&&categories().includes(urlCat))state.category=urlCat;renderCategoryStrip('#categoryRow',state.category,cat=>{state.category=cat;renderCategories();applyFilters()})}
  function applyFilters(){let r=state.channels.filter(c=>(state.category==='All'||c.category===state.category)&&(!state.search||`${c.name} ${c.category} ${c.country}`.toLowerCase().includes(state.search.toLowerCase())));if(state.sort==='az')r.sort((a,b)=>a.name.localeCompare(b.name));if(state.sort==='category')r.sort((a,b)=>a.category.localeCompare(b.category)||a.name.localeCompare(b.name));$('#resultCount').textContent=`${r.length} channels`;$('#channelGrid').innerHTML=r.length?r.map(card).join(''):`<div class="empty-state">No channels found.</div>`;bindCards('#channelGrid')}
  function setTheme(){document.documentElement.classList.toggle('light',state.theme==='light');$('#themeBtn').textContent=state.theme==='dark'?'☀':'☾'}
  function cleanup(){if(state.hls){try{state.hls.destroy()}catch{}state.hls=null}if(state.dash){try{state.dash.reset()}catch{}state.dash=null}const v=$('#videoPlayer');if(v){v.pause();v.removeAttribute('src');v.load();v.style.display='block'}const f=$('#embedPlayer');if(f){f.src='about:blank';f.style.display='none'}}
  function loading(on,msg='Starting live stream…'){$('#loadingOverlay').classList.toggle('hidden',!on);$('#loadingOverlay span').textContent=msg}
  function showError(msg){loading(false);$('#errorText').textContent=msg;$('#errorOverlay').classList.remove('hidden')}
  function openById(id){const c=state.channels.find(x=>x.id===id)||state.channels[0];if(!c){$('#playTitle').textContent='Channel not found';return}state.current=c;mark(c);$('#playTitle').textContent=c.name;$('#playCountry').textContent=c.country;$('#playCategory').textContent=c.category;$('#playType').textContent=type(c).toUpperCase();$('#playLogo').src=c.logo||'';$('#errorOverlay').classList.add('hidden');cleanup();loading(true);renderRelated(c);const t=type(c);if(t==='hls')return playHls(c);if(t==='dash')return playDash(c);if(t==='embed')return playEmbed(c);return playVideo(c)}
  function renderRelated(c){const related=state.channels.filter(x=>x.id!==c.id&&x.category===c.category).concat(state.channels.filter(x=>x.id!==c.id&&x.category!==c.category)).slice(0,18);$('#relatedCount').textContent=related.length;$('#relatedRow').innerHTML=related.length?related.map(card).join(''):'<div class="empty-shelf">No related channels.</div>';bindCards('#relatedRow')}
  function playHls(c){const v=$('#videoPlayer'),url=playable(c);v.style.display='block';if(v.canPlayType('application/vnd.apple.mpegurl')){v.src=url;v.onloadedmetadata=()=>{loading(false);v.play().catch(()=>{})};v.onerror=()=>showError('HLS stream could not be played.');return}if(!window.Hls?.isSupported())return showError('HLS is not supported on this device.');const h=new Hls({enableWorker:true,lowLatencyMode:true,startLevel:0,capLevelToPlayerSize:true,backBufferLength:4,maxBufferLength:7,maxMaxBufferLength:12,liveSyncDurationCount:1,liveMaxLatencyDurationCount:2,maxLiveSyncPlaybackRate:1.4,manifestLoadingMaxRetry:2,fragLoadingMaxRetry:2,levelLoadingMaxRetry:2,initialLiveManifestSize:1,maxBufferHole:.5});state.hls=h;h.loadSource(url);h.attachMedia(v);h.on(Hls.Events.MANIFEST_PARSED,()=>{loading(false);v.play().catch(()=>{})});h.on(Hls.Events.FRAG_BUFFERED,()=>{if(!v.paused)loading(false)});h.on(Hls.Events.ERROR,(_,d)=>{if(!d.fatal)return;if(d.type===Hls.ErrorTypes.NETWORK_ERROR){try{h.startLoad(-1);return}catch{}}if(d.type===Hls.ErrorTypes.MEDIA_ERROR){try{h.recoverMediaError();return}catch{}}showError('HLS playback failed. The stream may be offline.')})}
  function playVideo(c){const v=$('#videoPlayer');v.style.display='block';v.src=playable(c);v.onloadedmetadata=()=>{loading(false);v.play().catch(()=>{})};v.onerror=()=>showError('This video cannot be played by the browser.')}
  function playDash(c){const v=$('#videoPlayer');v.style.display='block';if(!window.dashjs)return showError('DASH player library unavailable.');const p=dashjs.MediaPlayer().create();state.dash=p;p.initialize(v,playable(c),true);p.on(dashjs.MediaPlayer.events.STREAM_INITIALIZED,()=>loading(false));p.on(dashjs.MediaPlayer.events.ERROR,()=>showError('DASH playback failed.'))}
  function playEmbed(c){const v=$('#videoPlayer'),f=$('#embedPlayer');v.style.display='none';f.style.display='block';let u=c.url;try{const x=new URL(u);if(x.hostname.includes('youtu.be'))u=`https://www.youtube.com/embed/${x.pathname.slice(1)}?autoplay=1&rel=0`;else if(x.hostname.includes('youtube.com')){const id=x.searchParams.get('v');if(id)u=`https://www.youtube.com/embed/${id}?autoplay=1&rel=0`}}catch{}f.src=u;f.onload=()=>loading(false)}
  function focusFirst(){setTimeout(()=>{const el=document.querySelector('.page:not(.hidden) .category-btn, .page:not(.hidden) .channel-card, .page:not(.hidden) .play-back a');el?.focus({preventScroll:true})},60)}
  function setup(){state.channels=allChannels();setTheme();$('#themeBtn').onclick=()=>{state.theme=state.theme==='dark'?'light':'dark';localStorage.setItem('iptv_theme',state.theme);setTheme()};$('#randomBtn').onclick=()=>{const c=state.channels[Math.floor(Math.random()*state.channels.length)];if(c)navigate(`/play?id=${encodeURIComponent(c.id)}`)};$('#searchInput').oninput=e=>{state.search=e.target.value.trim();document.querySelector('.search-wrap').classList.toggle('has-value',!!state.search);if(route()==='/channels')applyFilters();else if(route()==='/home')buildSearchHome()};$('#clearSearch').onclick=()=>{$('#searchInput').value='';state.search='';document.querySelector('.search-wrap').classList.remove('has-value');if(route()==='/channels')applyFilters();else renderHome()};$$('.sort-btn').forEach(b=>b.onclick=()=>{$$('.sort-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.sort=b.dataset.sort;applyFilters()});$('#retryBtn').onclick=()=>state.current&&openById(state.current.id);$('#reportBtn').onclick=()=>alert('Please report this channel to the site administrator.');window.addEventListener('popstate',renderRoute);document.addEventListener('keydown',tvKeys);renderRoute()}
  function buildSearchHome(){if(!state.search){renderHome();return}const q=state.search.toLowerCase();const found=state.channels.filter(c=>`${c.name} ${c.category} ${c.country}`.toLowerCase().includes(q));$('#homeShelves').innerHTML=`<section class="section shelf"><div class="section-title"><h2>Search results</h2><span>${found.length}</span></div><div class="rail">${found.length?found.map(card).join(''):'<div class="empty-shelf">No matching channels.</div>'}</div></section>`;bindCards('#homeShelves')}
  function tvKeys(e){const active=document.activeElement;if(!active?.classList.contains('channel-card')&&!active?.classList.contains('category-btn'))return;if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;const rail=active.closest('.rail,.category-strip');if(!rail)return;const items=[...rail.querySelectorAll(':scope > .channel-card, :scope > .category-btn')];const i=items.indexOf(active);let n=i;if(e.key==='ArrowLeft')n=Math.max(0,i-1);if(e.key==='ArrowRight')n=Math.min(items.length-1,i+1);if(e.key==='ArrowUp'||e.key==='ArrowDown'){const rails=[...document.querySelectorAll('.page:not(.hidden) .rail,.page:not(.hidden) .category-strip')];const ri=rails.indexOf(rail);const nr=ri+(e.key==='ArrowDown'?1:-1);if(nr>=0&&nr<rails.length){const next=[...rails[nr].querySelectorAll(':scope > .channel-card, :scope > .category-btn')];next[Math.min(i,next.length-1)]?.focus();e.preventDefault();return}}if(n!==i){items[n]?.focus();items[n]?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});e.preventDefault()}}
  document.addEventListener('DOMContentLoaded',setup);
})();
